name       : ruby-paint
version    : 2.1.1
release    : 6
source     :
    - https://rubygems.org/downloads/paint-2.1.1.gem : b01249af160d237b68df8abf23f8c1731857c3206aa1ff4085ce99e9c5152b67
license    : MIT
component  : programming.ruby
summary    : Ruby gem for ANSI terminal colors
description: |
    Paint creates terminal colors and effects for you. It combines the strengths of term-ansicolor, rainbow, and similar projects into a simple to use, however still flexible terminal colors gem with no core extensions by default.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby
install    : |
    %gem_install

    # Removing empty folders and unnecessary files.
    rm -rf $installdir/usr/lib64/ruby/gems/2.6.0/{build_info,doc,extensions}
    rm -rf $installdir/usr/lib64/ruby/gems/2.6.0/gems/paint-2.1.1/{CHANGELOG.md,MIT-LICENSE.txt,README.md}
