name       : ruby-paint
version    : 2.0.1
release    : 4
source     :
    - https://rubygems.org/downloads/paint-2.0.1.gem : 0d3c6dc920c3d6796e96f44f6bf0a20b6e995909ef86c257279c2006234bd0be
license    : MIT
component  : programming.ruby
summary    : Ruby gem for ANSI terminal colors
description: |
    Paint creates terminal colors and effects for you. It combines the strengths of term-ansicolor, rainbow, and similar projects into a simple to use, however still flexible terminal colors gem with no core extensions by default.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby
install    : |
    %gem_install
