name       : ruby-paint
version    : 2.2.0
release    : 9
source     :
    - https://rubygems.org/downloads/paint-2.2.0.gem : 7452eea1c91750f9b284773fae5fc3fb8f14dd1227e1c91988199bb7662e8b04
license    : MIT
component  : programming.ruby
summary    : Ruby gem for ANSI terminal colors
description: |
    Paint creates terminal colors and effects for you. It combines the strengths of term-ansicolor, rainbow, and similar projects into a simple to use, however still flexible terminal colors gem with no core extensions by default.
builddeps  :
    - pkgconfig(ruby-3.0)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
    rm -rf $installdir/$geminstalldir/gems/paint-$version/{CHANGELOG.md,MIT-LICENSE.txt,README.md}
